# Nome da aplicação
spring.application.name=coupon-api

# Porta padrão da aplicação
server.port=8080

# =========================
# H2 Database
# =========================
spring.datasource.url=jdbc:h2:mem:coupondb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Dialeto do H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# =========================
# H2 Console
# =========================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================
# Swagger / OpenAPI
# =========================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs